### ISSUE TITLE
Feature Request:  Filter by to-do type note.

### ISSUE THREAD

**Issue by thammawat-s** [joplin/plugin-kanban#15]
If Kanban could filter on note type instead/addition to tag, that would be ideal. I.e. I only want "to-do" notes to be in my Kanban (workaround is I tag them with "task" and filter on that). This way I keep the Joplin todo logic and added Kanban magic.

Regards,

**Comment by zhenjiaofenjie** [comment]
You could try the parameter `completed`. For example:
```kanban
columns:
    - name: Queue
      completed: false
    - name: Progressing
      completed: false
    - name: Finished
      completed: true
```

**Comment by ameisbe** [comment]
This actually works like this:

```
columns:
  - name: TODO
    tag: todo
  - name: Working
    tag: wip
  - name: Done
    completed: true
    tag: done
filters:
  rootNotebookPath: /
  completed: false
```
