### ISSUE TITLE
Feature request: horizontal grouping (swimlanes)

### ISSUE THREAD

**Issue by ctbarrett** [joplin/plugin-kanban#28]
It would be useful to organize a kanban board by grouping cards into horizontal swimlanes by project (bonus points if they were collapsible). Currently I have a single notebook for tasks, and I'm using tags for projects, but I may try using separate notebooks, and filtering projects via `notebookPath`. In either case, it would be great if I could visually group cards together by project, separately from the workflow states I assign to columns.

In terms of the config interface, I think something similar to the `columns:` map would work well. Some filters may not make sense in both columns and lanes (e.g. `completed` makes sense either in a column or a lane, but not both). I could see a few different ways to handle that part: having one dimension take precedence over the other where they intersect, ignoring some tags in the `lanes:` context, or defining a fixed set of filters that could be used.

**Example**

```yaml
lanes:
  - name: "Project A"
    tag: project-a
  - name: "Project B"
    tag: "project b"
  - name: "Group AwesomeSauce Other Stuff"
    notebookPath: "/Tasklist/World Domination (working copy)"
```
