### ISSUE TITLE
Feature request: Excluded tag filters

### ISSUE THREAD

**Issue by Ziron** [joplin/plugin-kanban#29]
Would it be possible to add an inverted tag selection to exclude certain tags from the list, instead of only specifying tags to show?

Like for example:
```yaml
filters:
  tag: !ignoredTag 
```
or
```yaml
filters:
  excludedTag: ignoredTag 
```

I think it would be very helpful!

**Comment by Ziron** [comment]
After looking at the source code I found the undocumented filter "excludeNoteId" which also is a great feature and solves my problem for now!
But it would be nice to be able to exclude notes more generally by tag.

**Comment by moonloop00** [comment]
Another example use case is to have an archive notebook (whose parent is tasks) to exclude from the completed column, because otherwise that will grow indefinitely

![image](https://user-images.githubusercontent.com/103313456/202154510-f7a3e7cb-8a2b-434b-9778-686ef41124e7.png)

kanban config 

```yml
columns:
  - name: Backlog
    backlog: true
  - name: Work in progress
    tag: wip
  - name: Finished
    tag: do
```
